<?php
/**
 * BaseFoundationModel
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowHunt
 *
 * FlowHunt API
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FlowHunt\Model;
use \FlowHunt\ObjectSerializer;

/**
 * BaseFoundationModel Class Doc Comment
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BaseFoundationModel
{
    /**
     * Possible values of this enum
     */
    public const FLUX_DEV = 'flux-dev';

    public const FLUX_SCHNELL = 'flux-schnell';

    public const STABLE_DIFFUSION_3_5_MEDIUM = 'stable-diffusion-3.5-medium';

    public const STABLE_DIFFUSION_3_5_LARGE_TURBO = 'stable-diffusion-3.5-large-turbo';

    public const STABLE_DIFFUSION_3_5_LARGE = 'stable-diffusion-3.5-large';

    public const IMAGEN_3 = 'imagen-3';

    public const IMAGEN_3_FAST = 'imagen-3-fast';

    public const IDEOGRAM_V2 = 'ideogram-v2';

    public const IDEOGRAM_V2_TURBO = 'ideogram-v2-turbo';

    public const IDEOGRAM_V2A = 'ideogram-v2a';

    public const IDEOGRAM_V2A_TURBO = 'ideogram-v2a-turbo';

    public const IDEOGRAM_V3_QUALITY = 'ideogram-v3-quality';

    public const IDEOGRAM_V3_TURBO = 'ideogram-v3-turbo';

    public const IDEOGRAM_V3_BALANCED = 'ideogram-v3-balanced';

    public const GPT_IMAGE_1_5 = 'gpt-image-1.5';

    public const SORA_2 = 'sora-2';

    public const NANO_BANANA = 'nano-banana';

    public const NANO_BANANA_PRO = 'nano-banana-pro';

    public const GEMINI_2_5_FLASH = 'gemini-2.5-flash';

    public const QWEN_IMAGE_EDIT_PLUS = 'qwen-image-edit-plus';

    public const QWEN_IMAGE = 'qwen-image';

    public const WAN_2_2_ANIMATE_REPLACE = 'wan-2.2-animate-replace';

    public const WAN_2_5_T2V_FAST = 'wan-2.5-t2v-fast';

    public const WAN_2_2_ANIMATE_ANIMATION = 'wan-2.2-animate-animation';

    public const WAN_2_5_I2V_FAST = 'wan-2.5-i2v-fast';

    public const WAN_2_5_I2V = 'wan-2.5-i2v';

    public const VEO_3_1 = 'veo-3.1';

    public const VEO_3_1_FAST = 'veo-3.1-fast';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FLUX_DEV,
            self::FLUX_SCHNELL,
            self::STABLE_DIFFUSION_3_5_MEDIUM,
            self::STABLE_DIFFUSION_3_5_LARGE_TURBO,
            self::STABLE_DIFFUSION_3_5_LARGE,
            self::IMAGEN_3,
            self::IMAGEN_3_FAST,
            self::IDEOGRAM_V2,
            self::IDEOGRAM_V2_TURBO,
            self::IDEOGRAM_V2A,
            self::IDEOGRAM_V2A_TURBO,
            self::IDEOGRAM_V3_QUALITY,
            self::IDEOGRAM_V3_TURBO,
            self::IDEOGRAM_V3_BALANCED,
            self::GPT_IMAGE_1_5,
            self::SORA_2,
            self::NANO_BANANA,
            self::NANO_BANANA_PRO,
            self::GEMINI_2_5_FLASH,
            self::QWEN_IMAGE_EDIT_PLUS,
            self::QWEN_IMAGE,
            self::WAN_2_2_ANIMATE_REPLACE,
            self::WAN_2_5_T2V_FAST,
            self::WAN_2_2_ANIMATE_ANIMATION,
            self::WAN_2_5_I2V_FAST,
            self::WAN_2_5_I2V,
            self::VEO_3_1,
            self::VEO_3_1_FAST
        ];
    }
}


