<?php
/**
 * DocumentType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowHunt
 *
 * FlowHunt API
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FlowHunt\Model;
use \FlowHunt\ObjectSerializer;

/**
 * DocumentType Class Doc Comment
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentType
{
    /**
     * Possible values of this enum
     */
    public const PDF = 'PDF';

    public const DOCX = 'DOCX';

    public const MD = 'MD';

    public const TXT = 'TXT';

    public const HTML = 'HTML';

    public const YT = 'YT';

    public const UN = 'UN';

    public const MP3 = 'MP3';

    public const FLAC = 'FLAC';

    public const MP4 = 'MP4';

    public const MPEG = 'MPEG';

    public const MPGA = 'MPGA';

    public const M4_A = 'M4A';

    public const OGG = 'OGG';

    public const WAV = 'WAV';

    public const WEBM = 'WEBM';

    public const JPEG = 'JPEG';

    public const JPG = 'JPG';

    public const PNG = 'PNG';

    public const GIF = 'GIF';

    public const WEBP = 'WEBP';

    public const GOOGLE_DOCS = 'GOOGLE_DOCS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PDF,
            self::DOCX,
            self::MD,
            self::TXT,
            self::HTML,
            self::YT,
            self::UN,
            self::MP3,
            self::FLAC,
            self::MP4,
            self::MPEG,
            self::MPGA,
            self::M4_A,
            self::OGG,
            self::WAV,
            self::WEBM,
            self::JPEG,
            self::JPG,
            self::PNG,
            self::GIF,
            self::WEBP,
            self::GOOGLE_DOCS
        ];
    }
}


