<?php
/**
 * FlowEventActionType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowHunt
 *
 * FlowHunt API
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FlowHunt\Model;
use \FlowHunt\ObjectSerializer;

/**
 * FlowEventActionType Class Doc Comment
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FlowEventActionType
{
    /**
     * Possible values of this enum
     */
    public const LOADING = 'loading';

    public const MESSAGE = 'message';

    public const TOOL_CALL = 'tool_call';

    public const TASK_RESPONSE = 'task_response';

    public const FAILED = 'failed';

    public const MESSAGE_FEEDBACK = 'message_feedback';

    public const ARTEFACTS = 'artefacts';

    public const AGENT_COT = 'agent_cot';

    public const TODO_LIST = 'todo_list';

    public const ADD_COMPONENT = 'add_component';

    public const DELETE_COMPONENT = 'delete_component';

    public const CONNECT_COMPONENTS = 'connect_components';

    public const UPDATE_COMPONENT = 'update_component';

    public const ADD_CONNECTION = 'add_connection';

    public const DELETE_CONNECTION = 'delete_connection';

    public const CREATE_BLANK_FLOW = 'create_blank_flow';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LOADING,
            self::MESSAGE,
            self::TOOL_CALL,
            self::TASK_RESPONSE,
            self::FAILED,
            self::MESSAGE_FEEDBACK,
            self::ARTEFACTS,
            self::AGENT_COT,
            self::TODO_LIST,
            self::ADD_COMPONENT,
            self::DELETE_COMPONENT,
            self::CONNECT_COMPONENTS,
            self::UPDATE_COMPONENT,
            self::ADD_CONNECTION,
            self::DELETE_CONNECTION,
            self::CREATE_BLANK_FLOW
        ];
    }
}


