<?php
/**
 * FlowAssistantAIModel
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowHunt
 *
 * FlowHunt API
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FlowHunt\Model;
use \FlowHunt\ObjectSerializer;

/**
 * FlowAssistantAIModel Class Doc Comment
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FlowAssistantAIModel
{
    /**
     * Possible values of this enum
     */
    public const CLAUDE_3_5_SONNET = 'Claude 3.5 Sonnet';

    public const CLAUDE_3_7_SONNET = 'Claude 3.7 Sonnet';

    public const GPT4_1 = 'GPT4.1';

    public const O4_MINI = 'O4 Mini';

    public const O3_MINI = 'O3 Mini';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CLAUDE_3_5_SONNET,
            self::CLAUDE_3_7_SONNET,
            self::GPT4_1,
            self::O4_MINI,
            self::O3_MINI
        ];
    }
}


