<?php
/**
 * IntegrationSlug
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowHunt
 *
 * FlowHunt API
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FlowHunt\Model;
use \FlowHunt\ObjectSerializer;

/**
 * IntegrationSlug Class Doc Comment
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IntegrationSlug
{
    /**
     * Possible values of this enum
     */
    public const SHOPIFY_INTEGRATION = 'shopify_integration';

    public const SLACK_INTEGRATION = 'slack_integration';

    public const HUBSPOT_INTEGRATION = 'hubspot_integration';

    public const LIVEAGENT_INTEGRATION = 'liveagent_integration';

    public const HUBSPOT_WIDGET_INTEGRATION = 'hubspot_widget_integration';

    public const LIVECHAT_INTEGRATION = 'livechat_integration';

    public const SMARTSUPP_INTEGRATION = 'smartsupp_integration';

    public const FRESHCHAT_INTEGRATION = 'freshchat_integration';

    public const TAWK_INTEGRATION = 'tawk_integration';

    public const GOOGLE_INTEGRATION = 'google_integration';

    public const WORDPRESS_INTEGRATION = 'wordpress_integration';

    public const GMAIL_INTEGRATION = 'gmail_integration';

    public const INSTAGRAM_INTEGRATION = 'instagram_integration';

    public const MICROSOFT_OUTLOOK_INTEGRATION = 'microsoft_outlook_integration';

    public const MICROSOFT_INTEGRATION = 'microsoft_integration';

    public const ODOO_INTEGRATION = 'odoo_integration';

    public const ATLASSIAN_TOKEN_INTEGRATION = 'atlassian_token_integration';

    public const BIZNISWEB_INTEGRATION = 'biznisweb_integration';

    public const BITRIX24_INTEGRATION = 'bitrix24_integration';

    public const API_SPORTS_INTEGRATION = 'api_sports_integration';

    public const GITHUB_INTEGRATION = 'github_integration';

    public const POWERBI_INTEGRATION = 'powerbi_integration';

    public const BEXIO_INTEGRATION = 'bexio_integration';

    public const MAILCHIMP_INTEGRATION = 'mailchimp_integration';

    public const LINKEDIN_INTEGRATION = 'linkedin_integration';

    public const MAGENTO2_INTEGRATION = 'magento2_integration';

    public const ALPACA_INTEGRATION = 'alpaca_integration';

    public const POLYGON_INTEGRATION = 'polygon_integration';

    public const POSTAFFILIATEPRO_INTEGRATION = 'postaffiliatepro_integration';

    public const KLAVIYO_INTEGRATION = 'klaviyo_integration';

    public const GOOGLE_CALENDAR_INTEGRATION = 'google_calendar_integration';

    public const GOOGLE_ADS_INTEGRATION = 'google_ads_integration';

    public const GOOGLE_DOCS_INTEGRATION = 'google_docs_integration';

    public const GOOGLE_DRIVE_INTEGRATION = 'google_drive_integration';

    public const GOOGLE_SHEETS_INTEGRATION = 'google_sheets_integration';

    public const GOOGLE_TASKS_INTEGRATION = 'google_tasks_integration';

    public const GOOGLE_MEET_INTEGRATION = 'google_meet_integration';

    public const GOOGLE_SLIDES_INTEGRATION = 'google_slides_integration';

    public const GOOGLE_SEARCH_CONSOLE_INTEGRATION = 'google_search_console_integration';

    public const MICROSOFT_CALENDAR_INTEGRATION = 'microsoft_calendar_integration';

    public const MICROSOFT_EXCEL_INTEGRATION = 'microsoft_excel_integration';

    public const MICROSOFT_ONEDRIVE_INTEGRATION = 'microsoft_onedrive_integration';

    public const MICROSOFT_SHAREPOINT_INTEGRATION = 'microsoft_sharepoint_integration';

    public const MICROSOFT_ONENOTE_INTEGRATION = 'microsoft_onenote_integration';

    public const MICROSOFT_TODO_INTEGRATION = 'microsoft_todo_integration';

    public const MICROSOFT_PLANNER_INTEGRATION = 'microsoft_planner_integration';

    public const MICROSOFT_OUTLOOK_CONTACTS_INTEGRATION = 'microsoft_outlook_contacts_integration';

    public const MICROSOFT_TEAMS_INTEGRATION = 'microsoft_teams_integration';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SHOPIFY_INTEGRATION,
            self::SLACK_INTEGRATION,
            self::HUBSPOT_INTEGRATION,
            self::LIVEAGENT_INTEGRATION,
            self::HUBSPOT_WIDGET_INTEGRATION,
            self::LIVECHAT_INTEGRATION,
            self::SMARTSUPP_INTEGRATION,
            self::FRESHCHAT_INTEGRATION,
            self::TAWK_INTEGRATION,
            self::GOOGLE_INTEGRATION,
            self::WORDPRESS_INTEGRATION,
            self::GMAIL_INTEGRATION,
            self::INSTAGRAM_INTEGRATION,
            self::MICROSOFT_OUTLOOK_INTEGRATION,
            self::MICROSOFT_INTEGRATION,
            self::ODOO_INTEGRATION,
            self::ATLASSIAN_TOKEN_INTEGRATION,
            self::BIZNISWEB_INTEGRATION,
            self::BITRIX24_INTEGRATION,
            self::API_SPORTS_INTEGRATION,
            self::GITHUB_INTEGRATION,
            self::POWERBI_INTEGRATION,
            self::BEXIO_INTEGRATION,
            self::MAILCHIMP_INTEGRATION,
            self::LINKEDIN_INTEGRATION,
            self::MAGENTO2_INTEGRATION,
            self::ALPACA_INTEGRATION,
            self::POLYGON_INTEGRATION,
            self::POSTAFFILIATEPRO_INTEGRATION,
            self::KLAVIYO_INTEGRATION,
            self::GOOGLE_CALENDAR_INTEGRATION,
            self::GOOGLE_ADS_INTEGRATION,
            self::GOOGLE_DOCS_INTEGRATION,
            self::GOOGLE_DRIVE_INTEGRATION,
            self::GOOGLE_SHEETS_INTEGRATION,
            self::GOOGLE_TASKS_INTEGRATION,
            self::GOOGLE_MEET_INTEGRATION,
            self::GOOGLE_SLIDES_INTEGRATION,
            self::GOOGLE_SEARCH_CONSOLE_INTEGRATION,
            self::MICROSOFT_CALENDAR_INTEGRATION,
            self::MICROSOFT_EXCEL_INTEGRATION,
            self::MICROSOFT_ONEDRIVE_INTEGRATION,
            self::MICROSOFT_SHAREPOINT_INTEGRATION,
            self::MICROSOFT_ONENOTE_INTEGRATION,
            self::MICROSOFT_TODO_INTEGRATION,
            self::MICROSOFT_PLANNER_INTEGRATION,
            self::MICROSOFT_OUTLOOK_CONTACTS_INTEGRATION,
            self::MICROSOFT_TEAMS_INTEGRATION
        ];
    }
}


