<?php
/**
 * OnboardingPrimaryGoal
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowHunt
 *
 * FlowHunt API
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FlowHunt\Model;
use \FlowHunt\ObjectSerializer;

/**
 * OnboardingPrimaryGoal Class Doc Comment
 *
 * @category Class
 * @description Primary goal selected by a user on the post-signup welcome screen.
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OnboardingPrimaryGoal
{
    /**
     * Possible values of this enum
     */
    public const AISTUDIO = 'aistudio';

    public const AI_PROJECTS = 'ai_projects';

    public const PHOTOAI = 'photoai';

    public const EXPLORE = 'explore';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AISTUDIO,
            self::AI_PROJECTS,
            self::PHOTOAI,
            self::EXPLORE
        ];
    }
}


