<?php
/**
 * FlowSessionSubagentPromptMetadataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowHunt
 *
 * FlowHunt API
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FlowHunt\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FlowSessionSubagentPromptMetadataTest Class Doc Comment
 *
 * @category    Class
 * @description Metadata for the prompt that a supervisor sends to a subagent.  Emitted from &#x60;&#x60;start_async_task&#x60;&#x60; when a delegating agent spawns a coworker workflow. Tagged with &#x60;&#x60;component_name&#x60;&#x60; &#x3D; the subagent&#39;s name and &#x60;&#x60;run_id&#x60;&#x60; &#x3D; the subagent&#39;s pyworkflow run, so it surfaces in the subagent&#39;s tab in the UI and in the &#x60;&#x60;check_async_task&#x60;&#x60; activity log.
 * @package     FlowHunt
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FlowSessionSubagentPromptMetadataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FlowSessionSubagentPromptMetadata"
     */
    public function testFlowSessionSubagentPromptMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "task"
     */
    public function testPropertyTask()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "started_by"
     */
    public function testPropertyStartedBy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "target_agent"
     */
    public function testPropertyTargetAgent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
