<?php
/**
 * ModelLimitsResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowHunt
 *
 * FlowHunt API
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FlowHunt\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ModelLimitsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ModelLimitsResponse
 * @package     FlowHunt
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ModelLimitsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ModelLimitsResponse"
     */
    public function testModelLimitsResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_outputs"
     */
    public function testPropertyMaxOutputs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "step_options"
     */
    public function testPropertyStepOptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "guidance_options"
     */
    public function testPropertyGuidanceOptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "duration_options"
     */
    public function testPropertyDurationOptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "default_steps"
     */
    public function testPropertyDefaultSteps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "min_steps"
     */
    public function testPropertyMinSteps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_steps"
     */
    public function testPropertyMaxSteps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_reference_images"
     */
    public function testPropertyMaxReferenceImages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "resolution_type"
     */
    public function testPropertyResolutionType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
