<?php
/**
 * AgentTeamProjectsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowHunt
 *
 * FlowHunt API
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace FlowHunt\Test\Api;

use \FlowHunt\Configuration;
use \FlowHunt\ApiException;
use \FlowHunt\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AgentTeamProjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AgentTeamProjectsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelChat
     *
     * Cancel Chat.
     *
     */
    public function testCancelChat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createProject
     *
     * Create Project.
     *
     */
    public function testCreateProject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAgentTeamProject
     *
     * Delete Agent Team Project.
     *
     */
    public function testDeleteAgentTeamProject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateSuggestions
     *
     * Generate Suggestions.
     *
     */
    public function testGenerateSuggestions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateTitle
     *
     * Generate Title.
     *
     */
    public function testGenerateTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProject
     *
     * Get Project.
     *
     */
    public function testGetProject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSuggestions
     *
     * Get Suggestions.
     *
     */
    public function testGetSuggestions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for hitlRespond
     *
     * Hitl Respond.
     *
     */
    public function testHitlRespond()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pollChat
     *
     * Poll Chat.
     *
     */
    public function testPollChat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pollGenerateAgentConfig
     *
     * Poll Generate Agent Config.
     *
     */
    public function testPollGenerateAgentConfig()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchProjects
     *
     * Search Projects.
     *
     */
    public function testSearchProjects()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for startChat
     *
     * Start Chat.
     *
     */
    public function testStartChat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for startGenerateAgentConfig
     *
     * Start Generate Agent Config.
     *
     */
    public function testStartGenerateAgentConfig()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for testChannelConnection
     *
     * Test Channel Connection.
     *
     */
    public function testTestChannelConnection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProject
     *
     * Update Project.
     *
     */
    public function testUpdateProject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
