<?php
/**
 * BillingApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowHunt
 *
 * FlowHunt API
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace FlowHunt\Test\Api;

use \FlowHunt\Configuration;
use \FlowHunt\ApiException;
use \FlowHunt\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BillingApiTest Class Doc Comment
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BillingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addAddonToSubscription
     *
     * Add Addon To Subscription.
     *
     */
    public function testAddAddonToSubscription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createChangePlanPortal
     *
     * Create Change Plan Portal.
     *
     */
    public function testCreateChangePlanPortal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCheckout
     *
     * Create Checkout.
     *
     */
    public function testCreateCheckout()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createUpdateInfoPortal
     *
     * Create Update Info Portal.
     *
     */
    public function testCreateUpdateInfoPortal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPricingPlans
     *
     * Get Pricing Plans.
     *
     */
    public function testGetPricingPlans()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserPlan
     *
     * Get User Plan.
     *
     */
    public function testGetUserPlan()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for stripeWebhook
     *
     * Stripe Webhook.
     *
     */
    public function testStripeWebhook()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
