<?php
/**
 * MemoryApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowHunt
 *
 * FlowHunt API
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace FlowHunt\Test\Api;

use \FlowHunt\Configuration;
use \FlowHunt\ApiException;
use \FlowHunt\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MemoryApiTest Class Doc Comment
 *
 * @category Class
 * @package  FlowHunt
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MemoryApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createNode
     *
     * Create Node.
     *
     */
    public function testCreateNode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNode
     *
     * Delete Node.
     *
     */
    public function testDeleteNode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getNode
     *
     * Get Node.
     *
     */
    public function testGetNode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processDocuments
     *
     * Process Documents.
     *
     */
    public function testProcessDocuments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchMemoryCategories
     *
     * Search Memory Categories.
     *
     */
    public function testSearchMemoryCategories()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchMemoryNodeName
     *
     * Search Memory Node Name.
     *
     */
    public function testSearchMemoryNodeName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchMemoryNodePath
     *
     * Search Memory Node Path.
     *
     */
    public function testSearchMemoryNodePath()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateNode
     *
     * Update Node.
     *
     */
    public function testUpdateNode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadDocument
     *
     * Upload Document.
     *
     */
    public function testUploadDocument()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
